name: pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Create config.js
        run: |
          echo "global.SALT_KEY = '${{ secrets.SALT_KEY }}';" > ./src/config.js
          echo "global.EMAIL_TMPL = 'Olá, <strong>{0}</strong>, seja bem vindo à Mask Shop!';" >> ./src/config.js
          echo "module.exports = {" >> ./src/config.js
          echo "  connectionString: '${{ secrets.MONGODB_CONNECTION }}'," >> ./src/config.js
          echo "  sendgridKey: '${{ secrets.SENDGRID_API_KEY }}'," >> ./src/config.js
          echo "  containerConnectionString: 'TBD'" >> ./src/config.js
          echo "};" >> ./src/config.js

      - name: Run tests
        run: npm test 

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: coverage

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
  
      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: maskshop-build
          path: dist

  notify:
    name: Notification
    runs-on: ubuntu-latest
    needs: 
      - build
      - test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
                
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install
                
      - name: Send email notification
        run: node scripts/send_notification.js
        env:
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}    
  
  

